# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('description', models.TextField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('status', models.NullBooleanField()),
            ],
        ),
    ]
