# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'In Stock'), ('2', 'Out Of Stock')], max_length=60, null=True),
        ),
    ]
