# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170221_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
