# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20170306_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
