# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20170309_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='none/img.jpg', upload_to='product/images/'),
        ),
    ]
