# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20170309_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IS', 'IN_STOCK'), ('OS', 'OUT_OF_STOCK')], max_length=1),
        ),
    ]
