# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20170309_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
