# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20170310_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='none/product1.jpg', upload_to='product/images/'),
        ),
    ]
