# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20170310_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phoneNumber',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
